src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', function () {
        return view('dashboard');
    })->name('root');
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
    Route::get('/settings', function () {
        return view('setting');
    });
    Route::get('/reviews', function () {
        return view('review');
    });
    Route::get('/bad-reviews', function () {
        return view('bad_review');
    });
    Route::get('profile', function () {
        return view('profile');
    })->name('profile');

    Route::get('customers', function () {
        return view('customer');
    })->name('customers');

    Route::get('templates', function () {
        return view('template');
    })->name('templates');

    Route::get('import_customers', function () {
        return view('import_customer');
    })->name('import_customers');

    Route::get('feedback',function(){
        return view('feedback');
    })->name('feedback');

    Route::get('send-sms', function () {
        return view('send-sms');
    })->name('send-sms');

    Route::get('members',function(){
        return view('members');
    })->name('members');

    Route::get('promotions',function(){
        return view('promotion');
    })->name('promotions');

    Route::get('promotion-at-risk',function(){
        return view('promotion_at_risk');
    })->name('promotion-at-risk');

    Route::get('/dashboard-checkin', function () {
        return view('dashboard-checkin');
    })->name('dashboard-checkin');

    Route::get('birthdays',function(){
        return view('birthdays');
    })->name('birthdays');

    Route::get('setting-checkin',function(){
        return view('setting-checkin');
    })->name('setting-checkin');
});

/*
 /--------------------------------------------------------------------
 / Route admin
 /--------------------------------------------------------------------
 */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    Route::get('/', function () {
        return view('admin.dashboard');
    })->name('root');

    Route::get('dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');

    Route::get('dashboard-agent', function () {
        return view('admin.dashboard_agent');
    })->name('root_agent');

    Route::get('access-user/{userId}/{redirectTo?}', 'DashboardController@accessUser');

    Route::get('agents', function () {
        return view('admin.users');
    })->name('agents');

    Route::get('users', function () {
        return view('admin.users');
    })->name('users');

    Route::get('notices', function () {
        return view('admin.notices');
    })->name('notices');

    Route::get('manage-background', function () {
        return view('admin.manage_background');
    })->name('manage_background');

    Route::get('settings',function(){
        return view('admin.settings');
    })->name('settings');

});

Route::get('callback/facebook/{store}/{provider}', 'CallbackController@facebookCallback')->name('callback.facebook');
Route::post(
    'stripe/webhook',
    '\App\Http\Controllers\StripeWebhookController@handleWebhook'
);
Route::get('/review/{shortId}/{step?}', 'ReviewRedirectController@index')->name('review.redirect');
Route::post('/review/{shortId}/{step?}', 'ReviewRedirectController@submit')->name('review.redirect.submit');
Route::get('/register-thanks', function () {
    return view('auth.register_thanks');
});
Route::get('/get-reviews-api', 'ApiGetReviews@get')->name('data.reviews');
Route::post('/api/insert-phone-store', 'ApiGetReviews@insertPhoneByStoreId')->name('insertPhoneByStoreId');
Route::get('/storage-link', function() {
	echo Artisan::call("storage:link");
});
Route::get('/cronjob/cronjob-run', 'CronjobAPIController@cronjobRun')->name('cronjob.cronjob_run');
Route::get('/cronjob/cronjob-birthday', 'CronjobAPIController@cronjobBirthday')->name('cronjob.cronjob_run_birthday');
Route::get('/check-in/{slug}', 'CheckInController@checkInByStoreSlug')->name('checkin.slug');
Route::get('/{slug}/{id}', 'ReviewRedirectController@redirectByStoreSlug')->name('review.redirect.slug.id');
Route::get('/{slug}', 'ReviewRedirectController@redirectByStoreSlug')->name('review.redirect.slug');

src/resources/views/layouts/admin/header.blade.php
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
  <!-- BEGIN HEADER INNER -->
  <div class="page-header-inner ">
    <!-- BEGIN LOGO -->
    <div class="page-logo">
      <a href="{!! route('admin.root') !!}">
        <img src="../assets/layouts/layout4/img/logo-blue.png" alt="logo" class="logo-default"/></a>

      <div class="menu-toggler sidebar-toggler">
        <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
      </div>
    </div>
    <!-- END LOGO -->
    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse"
       data-target=".navbar-collapse"> </a>
    <!-- END RESPONSIVE MENU TOGGLER -->
    <!-- BEGIN PAGE ACTIONS -->
    <!-- DOC: Remove "hide" class to enable the page header actions -->
    {{-- <div class="page-actions">
      <div class="btn-group">
        <button type="button" class="btn red-haze btn-sm">
          <span class="hidden-sm hidden-xs">Send Invite Request&nbsp;</span>
        </button>
      </div>
    </div> --}}
    <!-- END PAGE ACTIONS -->
    <!-- BEGIN PAGE TOP -->
    <div class="page-top">
      <!-- BEGIN HEADER SEARCH BOX -->
      <!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
      {{--<form class="search-form" action="page_general_search_2.html" method="GET">--}}
        {{--<div class="input-group">--}}
          {{--<input type="text" class="form-control input-sm" placeholder="Search..." name="query">--}}
                            {{--<span class="input-group-btn">--}}
                                {{--<a href="javascript:;" class="btn submit">--}}
                                  {{--<i class="icon-magnifier"></i>--}}
                                {{--</a>--}}
                            {{--</span>--}}
        {{--</div>--}}
      {{--</form>--}}
      <!-- END HEADER SEARCH BOX -->
      <!-- BEGIN TOP NAVIGATION MENU -->
      <div class="top-menu">
        <ul class="nav navbar-nav pull-right">
          <li class="separator hide"></li>
          <!-- BEGIN NOTIFICATION DROPDOWN -->
          <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
          {{--<li class="dropdown dropdown-extended dropdown-notification dropdown-dark" id="header_notification_bar">--}}
            {{--<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"--}}
               {{--data-close-others="true">--}}
              {{--<i class="icon-bell"></i>--}}
              {{--<span class="badge badge-success"> 7 </span>--}}
            {{--</a>--}}
            {{--<ul class="dropdown-menu">--}}
              {{--<li class="external">--}}
                {{--<h3>--}}
                  {{--<span class="bold">12 pending</span> notifications</h3>--}}
                {{--<a href="page_user_profile_1.html">view all</a>--}}
              {{--</li>--}}
              {{--<li>--}}
                {{--<ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">just now</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-success">--}}
                                                            {{--<i class="fa fa-plus"></i>--}}
                                                        {{--</span> New user registered. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">3 mins</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-danger">--}}
                                                            {{--<i class="fa fa-bolt"></i>--}}
                                                        {{--</span> Server #12 overloaded. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">10 mins</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-warning">--}}
                                                            {{--<i class="fa fa-bell-o"></i>--}}
                                                        {{--</span> Server #2 not responding. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">14 hrs</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-info">--}}
                                                            {{--<i class="fa fa-bullhorn"></i>--}}
                                                        {{--</span> Application error. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">2 days</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-danger">--}}
                                                            {{--<i class="fa fa-bolt"></i>--}}
                                                        {{--</span> Database overloaded 68%. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">3 days</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-danger">--}}
                                                            {{--<i class="fa fa-bolt"></i>--}}
                                                        {{--</span> A user IP blocked. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">4 days</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-warning">--}}
                                                            {{--<i class="fa fa-bell-o"></i>--}}
                                                        {{--</span> Storage Server #4 not responding dfdfdfd. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">5 days</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-info">--}}
                                                            {{--<i class="fa fa-bullhorn"></i>--}}
                                                        {{--</span> System Error. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">9 days</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-danger">--}}
                                                            {{--<i class="fa fa-bolt"></i>--}}
                                                        {{--</span> Storage server failed. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                {{--</ul>--}}
              {{--</li>--}}
            {{--</ul>--}}
          {{--</li>--}}
          <!-- END NOTIFICATION DROPDOWN -->
          <li class="separator hide"></li>
          <!-- BEGIN USER LOGIN DROPDOWN -->
          <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
          <li class="dropdown dropdown-user dropdown-dark">
            <a href="javascript:;" class="dropdown-toggle hidden-xs" data-toggle="dropdown" data-hover="dropdown"
               data-close-others="true">
              <span class="username username-hide-on-mobile"> {{ Auth::user()->full_name }} </span>
              <!-- DOC: Do not remove below empty space(&nbsp;) as its purposely used -->
              <img alt="" class="img-circle" src="../assets/layouts/layout4/img/avatar.png"/> </a>
            <ul class="dropdown-menu dropdown-menu-default">
              <li>
                <a href="{!! url('profile') !!}">
                  <i class="icon-user"></i> My Profile </a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="{!! url('/logout') !!}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                  <i class="icon-key"></i> Log Out </a>

                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                </form>
              </li>
            </ul>
          </li>
          <!-- END USER LOGIN DROPDOWN -->
        </ul>
      </div>
      <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END PAGE TOP -->
  </div>
  <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->

src/resources/views/layouts/admin/menu.blade.php
<?php if(Auth::user()->role == 2) { ?>
<li class="{!! Request::is('admin') || Request::is('admin/dashboard-agent*') ? 'active' : '' !!}">
    <a href="{!! url('admin/dashboard-agent') !!}" class="nav-link nav-toggle">
        <i class="icon-home"></i>
        <span class="title">Dashboard</span>
    </a>
</li>
<li class="{!! Request::is('admin/users') ? 'active' : '' !!}">
    <a href="{!! url('admin/users') !!}" class="nav-link nav-toggle">
        <i class="icon-users"></i>
        <span class="title">Users</span>
    </a>
</li>
<?php } else { ?>
<li class="{!! Request::is('admin') || Request::is('admin/dashboard*') ? 'active' : '' !!}">
    <a href="{!! url('admin/dashboard') !!}" class="nav-link nav-toggle">
        <i class="icon-home"></i>
        <span class="title">Dashboard</span>
    </a>
</li>

<li class="{!! Request::is('admin/notices') ? 'active' : '' !!}">
    <a href="{!! url('admin/notices') !!}" class="nav-link nav-toggle">
        <i class="icon-flag"></i>
        <span class="title">Notices</span>
    </a>
</li>
<li class="{!! Request::is('admin/agents') ? 'active' : '' !!}">
    <a href="{!! url('admin/agents') !!}" class="nav-link nav-toggle">
        <i class="icon-users"></i>
        <span class="title">Agents</span>
    </a>
</li>
<li class="{!! Request::is('admin/users') ? 'active' : '' !!}">
    <a href="{!! url('admin/users') !!}" class="nav-link nav-toggle">
        <i class="icon-users"></i>
        <span class="title">Users</span>
    </a>
</li>
<li class="{!! Request::is('admin/manage-background') ? 'active' : '' !!}">
    <a href="{!! url('admin/manage-background') !!}" class="nav-link nav-toggle">
        <i class="icon-picture"></i>
        <span class="title">Backgrounds</span>
    </a>
</li>
<li class="{!! Request::is('admin/settings') ? 'active' : '' !!}">
    <a href="{!! url('admin/settings') !!}" class="nav-link nav-toggle">
        <i class="icon-power"></i>
        <span class="title">Setting</span>
    </a>
</li>
<?php } ?>

src/resources/views/layouts/admin/sidebar.blade.php
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
        <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
        <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
        <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <ul class="page-sidebar-menu   " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            @include('layouts.admin.menu')

        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>
<!-- END SIDEBAR -->